FROM alpine:3.13
# tftp applet moved to busybox-extras as of
# https://git.alpinelinux.org/cgit/aports/commit/main/busybox?id=23f4c6bd6c0c8c8f616facad94865e7961cdfb2d
RUN apk add --no-cache busybox-extras
