#!/bin/sh
set -e

. script/functions

echo
echo "===> Show image sizes."
docker images | egrep 'rsyslog\b'

echo
echo "===> Start a syslog server container."
docker rm -f rsyslog &> /dev/null || :
smitty docker run -d -h $(hostname) --name rsyslog -v /tmp/syslogdev:/dev rsyslog

echo
echo "===> Show rsyslog build options."
smitty docker run --rm -t rsyslog -v

echo
echo "===> Submit a test log message."
md5sum=$(date | md5sum | awk '{print $1}')
type logger
smitty logger -st jumanjitest $md5sum

echo
echo "===> Show server log."
smitty docker logs rsyslog | tee /tmp/copy-of-logs.out
echo
smitty grep $md5sum /tmp/copy-of-logs.out
