#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################

. ci/functions.sh

main() {
  setup_python_path
  install_precommit
  add_upstream_git_remote
  fetch_upstream
}

setup_python_path() {
  PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

install_precommit() {
  pip install \
    --compile \
    --disable-pip-version-check \
    --no-cache-dir \
    --quiet \
    --user \
    --verbose \
    -r ci/requirements.txt
}

add_upstream_git_remote() {
  if ! git remote show upstream &>/dev/null; then
    git remote add upstream https://github.com/jumanjihouse/docker-rsyslog.git
  fi

  # Allow user to easily get pull requests.
  if ! git config --get remote.upstream.fetch &>/dev/null; then
    git config --add remote.upstream.fetch +refs/pull/*/head:refs/remotes/upstream/pr/*
  fi
}

fetch_upstream() {
  git fetch upstream
}

main
