#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build the docker image(s). Invoke as "ci/build".
################################################################################

cat >ci/vars <<EOF
declare -rx  VERSION="8.1904.0-r1"
declare -rx  BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx  VCS_REF=$(git rev-parse --short HEAD)
declare -rx  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
declare -rx  CI_BUILD_URL=${CIRCLE_BUILD_URL:-unknown}
EOF

. ci/vars
. ci/functions.sh

echo
echo "===> Build a tiny rsyslog image."
run docker-compose build

echo
echo "WARN: you should docker tag the image with \"ci/tag\""
echo
