#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Publish image(s) to the docker hub.
################################################################################

. ci/vars
. ci/functions.sh

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker-compose -f docker-compose-metadata.yaml push
docker logout

curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/rsyslog/xavcu9-i4CI3Fwqrg_w2XYRFwxE='
