#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Tag images.
################################################################################

. ci/vars
. ci/functions.sh

run docker tag rsyslog jumanjiman/rsyslog:"${TAG}"
run docker tag rsyslog jumanjiman/rsyslog:latest
