#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Tag images.
################################################################################

cat >ci/vars <<EOF
declare -rx  VERSION=$(docker-compose run rsyslog-version 2>/dev/null | grep -o '[0-9a-zA-Z._\-]*')
declare -rx  BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx  VCS_REF=$(git rev-parse --short HEAD)
declare -rx  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
declare -rx  CI_BUILD_URL=${CIRCLE_BUILD_URL:-unknown}
EOF

. ci/vars
. ci/functions.sh

run docker-compose -f docker-compose-metadata.yaml build
run docker tag rsyslog jumanjiman/rsyslog:latest
