#!/bin/sh
set -e

. ci/vars
. ci/functions

echo
echo "===> Show image sizes."
docker images | egrep 'rsyslog\b'

echo
echo "===> Start a syslog server container."
smitty docker-compose up -d rsyslog

echo
echo "===> Start a tftpd container."
smitty docker-compose up -d tftpd

echo
echo "===> Fetch a file from tftpd"
smitty docker-compose run tftp

echo
echo "===> Show rsyslog build options."
smitty docker-compose exec rsyslog rsyslogd -v

echo
echo "===> Submit a test log message."
md5sum=$(date | md5sum | awk '{print $1}')
smitty docker-compose run --rm -e md5sum=${md5sum} logger

echo
echo "===> Show server log."
smitty docker-compose logs rsyslog | tee /tmp/copy-of-logs.out
echo
smitty grep $md5sum /tmp/copy-of-logs.out
smitty grep 'RRQ from 192.168.254.200' /tmp/copy-of-logs.out

echo
echo "===> Remove crufty containers."
docker-compose down
