#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/vars
. ci/bootstrap

echo
echo '===> Run pre-commit framework.'
run pre-commit run --all-files --verbose --hook-stage manual

echo
echo "===> Show image sizes."
run docker images | grep -E 'rsyslog\b'

echo
echo "===> Show labels."
run docker inspect -f '{{ .Config.Labels }}' rsyslog | tr ' ' '\n'

echo
echo "===> Start a syslog server container."
run docker-compose up -d rsyslog

echo
echo "===> Start a tftpd container."
run docker-compose up -d tftpd

echo
echo "===> Fetch a file from tftpd"
run docker-compose run tftp

echo
echo "===> Show rsyslog build options."
run docker-compose run --rm rsyslog-compile-options

echo
echo "===> Submit a test log message."
readonly md5sum="$(date | md5sum | awk '{print $1}')"
run docker-compose run --rm -e md5sum="${md5sum}" logger

echo
echo "===> Show server log."
run docker-compose logs rsyslog | tee /tmp/copy-of-logs.out
echo
run grep "${md5sum}" /tmp/copy-of-logs.out
run grep 'RRQ from 192.168.254.200' /tmp/copy-of-logs.out

echo
echo "===> Remove crufty containers."
run docker-compose down
echo
echo
